DomainFolder: /Users/shg096/Desktop/CanadaAonOut/domain/              # folder where the domain will be saved, ending with /
TempFolder: /Users/shg096/Desktop/CanadaAonOut/Tempdomain/            # folder where the temporary domain will be saved, ending with /
LakeFile: /Volumes/F:/hydrography/hydrolakes/HydroLAKES_polys_v10_shp/HydroLAKES_polys_v10_shp/HydroLAKES_polys_v10.shp # lake and reservoir shapefile; hydrolakes version v1.0
# flag to burn lakes into the river network; Always set to True
IncludeLakes: True

MeritBasinsLocations:
  # based on https://www.reachhydro.org/home/params/merit-basins
  # bugfixed files: MERIT-Basins hydrography (based on MERIT-Hydro v0.7/v1.0_bugfix1, minor bug fix for coastline pixels
  RivPath: /Users/shg096/Desktop/MERIT_Hydro/riv/                           # folder where the river segments are save, ending with /
  CatPath: /Users/shg096/Desktop/MERIT_Hydro/cat/                           # folder where the cat are saved, ending with /
  CstPath: /Users/shg096/Desktop/MERIT_Hydro/hill/                          # folder where the costal hillslope are, ending with /
  RivFileTemplate: riv_pfaf_*_MERIT_Hydro_v07_Basins_v01_bugfix1.shp        # pattern of riv files inside riv_path folder, ending with /
  CatFileTemplate: cat_pfaf_*_MERIT_Hydro_v07_Basins_v01_bugfix1.shp        # pattern of riv files inside riv_path folder, ending with /
  CstFileTemplate: hillslope_*_clean.shp                                    # pattern of riv files inside riv_path folder, ending with /

pfafs:
  - '71'
  - '72'
  - '73'
  - '74'
  - '75'
  - '76'
  - '77'
  - '78'
  # - '81'
  # - '82'
  # - '83'
  # - '84'
  # - '85'
