DomainFolder: /Users/shg096/Desktop/LakeRiverOut/domain/              # folder where the domain will be saved, ending with /
TempFolder: /Users/shg096/Desktop/LakeRiverOut/Tempdomain/            # folder where the temporary domain will be saved, ending with /
LakeFile: /Volumes/F:/hydrography/hydrolakes/HydroLAKES_polys_v10_shp/HydroLAKES_polys_v10_shp/HydroLAKES_polys_v10.shp # lake and reservoir shapefile; hydrolakes version v1.0
# flag to burn lakes into the river network; Always set to True
IncludeLakes: True

HDMAPaths:
  # based on https://www.reachhydro.org/home/params/merit-basins
  # bugfixed files: MERIT-Basins hydrography (based on MERIT-Hydro v0.7/v1.0_bugfix1, minor bug fix for coastline pixels
  RivPath: /Volumes/F:/hydrography/HDMA/processed/                           # folder where the river segments are save, ending with /
  CatPath: /Volumes/F:/hydrography/HDMA/processed/                           # folder where the cat are saved, ending with /
  RivFileTemplate: hdma_global_stream.shp                                   # pattern of riv files inside riv_path folder, ending with /
  CatFileTemplate: hdma_global_catch_v2_*000000.gpkg                        # pattern of riv files inside riv_path folder, ending with /


pfafs:
  # - '1'
  # - '2'
  - '3' # north america
  # - '4'
  # - '5'
  # - '6'
